-- Find properties in NY/OH that have changed features over time in MLS data
WITH mls_snapshots AS (
  SELECT
    CC_PROPERTY_ID,
    RECORD_DATE_TIME,
    YEAR_BUILT,
    BEDROOMS,
    FULL_BATHS,
    HALF_BATHS,
    GLA_SQFT,
    GARAGE_SPACES,
    ROOMS,
    ROW_NUMBER() OVER (PARTITION BY CC_PROPERTY_ID ORDER BY RECORD_DATE_TIME) AS snapshot_num
  FROM ROC_MLS_DATA.ATTOM.MLS
  WHERE CC_PROPERTY_ID IN (
    -- Get properties that have multiple snapshots
    SELECT CC_PROPERTY_ID
    FROM ROC_MLS_DATA.ATTOM.MLS
    GROUP BY CC_PROPERTY_ID
    HAVING COUNT(DISTINCT RECORD_DATE_TIME) >= 2
  )
),
first_snapshot AS (
  SELECT * FROM mls_snapshots WHERE snapshot_num = 1
),
last_snapshot AS (
  SELECT *
  FROM mls_snapshots ms
  WHERE snapshot_num = (
    SELECT MAX(snapshot_num)
    FROM mls_snapshots ms2
    WHERE ms2.CC_PROPERTY_ID = ms.CC_PROPERTY_ID
  )
)

SELECT
  f.CC_PROPERTY_ID,
  a.SITUSSTATE,
  a.SITUSCITY,
  a.SITUSZIP5,

  -- First snapshot
  f.RECORD_DATE_TIME AS FIRST_LISTING_DATE,
  f.BEDROOMS AS FIRST_BEDROOMS,
  f.FULL_BATHS AS FIRST_FULL_BATHS,
  f.HALF_BATHS AS FIRST_HALF_BATHS,
  f.GLA_SQFT AS FIRST_SQFT,

  -- Last snapshot
  l.RECORD_DATE_TIME AS LAST_LISTING_DATE,
  l.BEDROOMS AS LAST_BEDROOMS,
  l.FULL_BATHS AS LAST_FULL_BATHS,
  l.HALF_BATHS AS LAST_HALF_BATHS,
  l.GLA_SQFT AS LAST_SQFT,

  -- Changes
  (l.BEDROOMS - f.BEDROOMS) AS BEDROOM_CHANGE,
  (l.FULL_BATHS - f.FULL_BATHS) AS FULL_BATH_CHANGE,
  (l.HALF_BATHS - f.HALF_BATHS) AS HALF_BATH_CHANGE,
  (l.GLA_SQFT - f.GLA_SQFT) AS SQFT_CHANGE,

  -- Property details
  a.YEARBUILT,
  a.LOTSIZESQFT

FROM first_snapshot f
INNER JOIN last_snapshot l ON f.CC_PROPERTY_ID = l.CC_PROPERTY_ID
LEFT JOIN ROC_PUBLIC_RECORD_DATA.DATATREE.ASSESSOR a
  ON f.CC_PROPERTY_ID = a.PROPERTYID
  AND a.MARKETYEAR = (
    SELECT MAX(MARKETYEAR)
    FROM ROC_PUBLIC_RECORD_DATA.DATATREE.ASSESSOR a2
    WHERE a2.PROPERTYID = a.PROPERTYID
  )

WHERE
  -- Filter for NY and OH
  (
    (UPPER(a.SITUSSTATE) IN ('NY', 'NEW YORK')
     AND a.SITUSZIP5 NOT LIKE '100%' AND a.SITUSZIP5 NOT LIKE '101%'
     AND a.SITUSZIP5 NOT LIKE '102%' AND a.SITUSZIP5 NOT LIKE '103%'
     AND a.SITUSZIP5 NOT LIKE '104%' AND a.SITUSZIP5 NOT LIKE '112%'
     AND a.SITUSZIP5 NOT LIKE '113%' AND a.SITUSZIP5 NOT LIKE '114%'
     AND a.SITUSZIP5 NOT LIKE '116%')
    OR UPPER(a.SITUSSTATE) IN ('OH', 'OHIO')
  )
  -- Only keep properties where features actually changed
  AND (
    l.BEDROOMS != f.BEDROOMS
    OR l.FULL_BATHS != f.FULL_BATHS
    OR l.HALF_BATHS != f.HALF_BATHS
    OR ABS(l.GLA_SQFT - f.GLA_SQFT) > 100
  )

ORDER BY a.SITUSSTATE, a.SITUSZIP5;